ADS_PAGE_KEY = "ads"
ADS_CREATE_ROUTE = "Ads"
CREATIVE_REFRESH_PAGE_KEY = "ads_creative_refresh"
CREATIVE_REFRESH_ROUTE = "Creative Refresh"

ADS_ROUTES = (
    ADS_CREATE_ROUTE,
    CREATIVE_REFRESH_ROUTE,
)

ADS_NAV_LABELS = {
    ADS_CREATE_ROUTE: "Create Ads",
    CREATIVE_REFRESH_ROUTE: CREATIVE_REFRESH_ROUTE,
}
