ADS_PAGE_KEY = "ads"
ADS_CREATE_ROUTE = "Ads"
CREATIVE_REFRESH_PAGE_KEY = "ads_creative_refresh"
CREATIVE_REFRESH_ROUTE = "Creative Refresh"
POSTING_PAGE_KEY = "ads_posting"
POSTING_ROUTE = "Posting"

ADS_ROUTES = (
    ADS_CREATE_ROUTE,
    CREATIVE_REFRESH_ROUTE,
    POSTING_ROUTE,
)

ADS_NAV_LABELS = {
    ADS_CREATE_ROUTE: "New Ads",
    CREATIVE_REFRESH_ROUTE: CREATIVE_REFRESH_ROUTE,
    POSTING_ROUTE: POSTING_ROUTE,
}
