"""Read-only contract for the reviewed CRM schema; never runs DDL on page load."""


def schema_issues(cur):
    cur.execute("SELECT table_name,column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=ANY(%s)", (list(COLUMNS),))
    found = {}
    for row in cur.fetchall():
        found.setdefault(row['table_name'], set()).add(row['column_name'])
    issues = []
    for table, columns in COLUMNS.items():
        if table not in found:
            issues.append('missing public.' + table)
        else:
            issues.extend('missing public.' + table + '.' + column for column in columns if column not in found[table])
    cur.execute("SELECT c.relname,c.relrowsecurity FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind='r' AND c.relname=ANY(%s)", (list(COLUMNS),))
    issues.extend('RLS disabled: public.' + r['relname'] for r in cur.fetchall() if not r['relrowsecurity'])
    cur.execute("SELECT indexname FROM pg_indexes WHERE schemaname='public' AND indexname=ANY(%s)", (list(INDEXES),))
    existing = {r['indexname'] for r in cur.fetchall()}
    issues.extend('missing index ' + name for name in INDEXES if name not in existing)
    return issues

COLUMNS = {'crm_automation_enrollments': ('automation_id',
                                'created_at',
                                'current_step',
                                'id',
                                'last_checked_at',
                                'next_due_at',
                                'shopify_customer_id',
                                'status',
                                'steps',
                                'stop_reason',
                                'trigger_at',
                                'trigger_key',
                                'trigger_shopify_id',
                                'updated_at'),
 'crm_automations': ('activated_at',
                     'automation_key',
                     'config',
                     'id',
                     'name',
                     'status',
                     'steps',
                     'trigger_type',
                     'updated_at'),
 'crm_campaign_drafts': ('archived_at',
                         'created_at',
                         'created_by',
                         'document',
                         'id',
                         'last_test_resend_id',
                         'last_tested_at',
                         'name',
                         'status',
                         'tested_version',
                         'updated_at',
                         'version'),
 'crm_campaign_history': ('action',
                          'actor',
                          'after_value',
                          'before_value',
                          'campaign_id',
                          'created_at',
                          'id',
                          'version'),
 'crm_campaigns': ('created_at',
                   'id',
                   'name',
                   'recipient_cursor',
                   'resume_status',
                   'scheduled_at',
                   'segment_definition_id',
                   'shopify_segment_id',
                   'snapshot_at',
                   'status',
                   'template_id',
                   'template_version',
                   'updated_at'),
 'crm_delivery_events': ('event_id',
                         'event_type',
                         'hard_bounce',
                         'occurred_at',
                         'provider_id',
                         'received_at',
                         'send_id',
                         'test_id'),
 'crm_internal_tests': ('accepted_at',
                        'actor',
                        'campaign_id',
                        'campaign_version',
                        'created_at',
                        'error_category',
                        'id',
                        'provider_id',
                        'recipient',
                        'render_hash',
                        'sender',
                        'status'),
 'crm_marketing_events': ('created_at',
                          'event_id',
                          'event_type',
                          'link_host',
                          'occurred_at',
                          'provider_email_id',
                          'recipient_hash'),
 'crm_marketing_sends': ('attempts',
                         'campaign_id',
                         'created_at',
                         'due_at',
                         'enrollment_id',
                         'error_code',
                         'first_submitted_at',
                         'id',
                         'idempotency_key',
                         'lease_token',
                         'lease_until',
                         'provider_email_id',
                         'recipient_hash',
                         'request_hash',
                         'shopify_customer_id',
                         'status',
                         'step_index',
                         'template_id',
                         'template_version',
                         'test_recipient',
                         'test_send',
                         'updated_at'),
 'crm_order_attribution': ('amount',
                           'campaign_id',
                           'campaign_key',
                           'checked_at',
                           'currency',
                           'eligible',
                           'model',
                           'order_created_at',
                           'shopify_order_id',
                           'visit_at'),
 'crm_runtime_state': ('key', 'updated_at', 'value'),
 'crm_segment_definitions': ('created_by', 'id', 'name', 'rules', 'system_key', 'updated_at'),
 'crm_settings_history': ('actor', 'created_at', 'id', 'key', 'value', 'version'),
 'crm_suppressions': ('active',
                      'campaign_reference',
                      'created_at',
                      'email_for_provider',
                      'provider_reference',
                      'provider_synced',
                      'reason',
                      'recipient_hash',
                      'shopify_customer_id',
                      'shopify_sync_attempts',
                      'shopify_sync_checked_at',
                      'shopify_sync_error',
                      'shopify_sync_state',
                      'source',
                      'updated_at'),
 'crm_template_versions': ('content', 'created_at', 'template_id', 'version'),
 'crm_templates': ('archived_at',
                   'content',
                   'id',
                   'kind',
                   'name',
                   'template_key',
                   'updated_at',
                   'version'),
 'crm_webhook_events': ('attempts',
                        'error_code',
                        'event_id',
                        'lease_token',
                        'lease_until',
                        'object_id',
                        'occurred_at',
                        'processed_at',
                        'provider',
                        'received_at',
                        'related_customer_id',
                        'status',
                        'topic'),
 'crm_website_events': ('campaign_key',
                        'event_id',
                        'event_type',
                        'occurred_at',
                        'product_ref',
                        'received_at',
                        'session_ref',
                        'test_context'),
 'crm_workspace_settings': ('key', 'updated_at', 'updated_by', 'value', 'version')}
INDEXES = ('crm_enrollment_due_idx', 'crm_enrollment_customer_idx', 'crm_enrollment_trigger_idx', 'crm_campaign_status_idx', 'crm_send_due_idx', 'crm_send_customer_idx', 'crm_event_provider_idx', 'crm_event_date_idx', 'crm_suppression_customer_idx', 'crm_webhook_pending_idx', 'crm_campaign_drafts_updated_idx', 'crm_campaign_history_campaign_idx', 'crm_internal_tests_campaign', 'crm_delivery_events_provider', 'crm_website_events_campaign', 'crm_website_events_received', 'crm_order_attribution_campaign')
