// Execute the metadata repair in isolated PostgreSQL, never production.
import {PGlite} from './fixtures/crm/node_modules/@electric-sql/pglite/dist/index.js';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`
CREATE TABLE edition_products(id int primary key,shopify_product_gid text,shopify_handle text,next_edition_number int,sold_count int,remaining_count int);
CREATE TABLE shopify_orders(shopify_order_id text primary key,order_name text,customer_name text,raw_json jsonb,raw jsonb,updated_at timestamptz);
CREATE TABLE shopify_order_lines(id int primary key,shopify_order_id text,shopify_line_item_id text,product_title text,quantity int,sku text,variant_title text,raw_json jsonb,updated_at timestamptz);
CREATE TABLE edition_orders(id int primary key,shopify_order_id text,shopify_line_item_id text,shopify_product_gid text,edition_number int,edition_total int,variant_title text,updated_at timestamptz);
CREATE TABLE audit_logs(event_type text,entity_type text,entity_id text,shopify_order_id text,shopify_line_item_id text,shopify_handle text,old_value jsonb,new_value jsonb,reason text,actor text,source text);
INSERT INTO edition_products VALUES(723,'gid://shopify/Product/15399569064243','tom-brady-further-to-go',2,1,99);
INSERT INTO shopify_orders VALUES('gid://shopify/Order/18924580208947','#SC3232','Daniel Marshall','{"shipping_method":"Australia Post","line_items":[{"shopify_line_item_id":"gid://shopify/LineItem/50761092759859","variant_title":""}]}','{}',now());
INSERT INTO shopify_order_lines VALUES(5803,'gid://shopify/Order/18924580208947','gid://shopify/LineItem/50761092759859','Tom Brady Motivational Quote Art',1,'TBRADYA3','','{}',now());
INSERT INTO edition_orders VALUES(608,'gid://shopify/Order/18924580208947','gid://shopify/LineItem/50761092759859','gid://shopify/Product/15399569064243',1,100,'',now());
INSERT INTO shopify_orders VALUES('other','#OTHER','Other','{}','{}',now());
INSERT INTO shopify_order_lines VALUES(999,'other','other-line','Other',1,'OTHER','Black / S','{}',now());
`);
const productBefore=(await db.query('SELECT * FROM edition_products')).rows;
const otherBefore=(await db.query("SELECT * FROM shopify_order_lines WHERE id=999")).rows;
const sql=readFileSync(new URL('../scripts/repair_sc3232_variant.sql',import.meta.url),'utf8');
await db.exec(sql);
const order=(await db.query("SELECT * FROM shopify_orders WHERE order_name='#SC3232'")).rows[0];
assert.equal(order.raw_json.shipping_method,'Standard Shipping');
assert.equal(order.raw_json.shipping_carrier,'Australia Post');
assert.match(order.raw_json.line_items[0].variant_title,/Unframed \/ M/);
assert.deepEqual((await db.query('SELECT * FROM edition_products')).rows,productBefore);
assert.deepEqual((await db.query('SELECT * FROM shopify_order_lines WHERE id=999')).rows,otherBefore);
assert.deepEqual((await db.query('SELECT edition_number,edition_total FROM edition_orders')).rows,[{edition_number:1,edition_total:100}]);
await db.exec(sql);
assert.equal((await db.query('SELECT count(*)::int n FROM audit_logs')).rows[0].n,1);
assert.equal((await db.query('SELECT count(*)::int n FROM edition_orders')).rows[0].n,1);
assert.deepEqual((await db.query('SELECT * FROM edition_products')).rows,productBefore);
await db.close();
console.log('PASS metadata repair, carrier preservation, unchanged edition/counters, unrelated order isolation, idempotency (9 assertions)');
