const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const started=Date.now();const browser=await chromium.launch({channel:process.env.TEST_BROWSER||'msedge',headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8876');await page.getByText('Wall Preview Inbox',{exact:true}).waitFor();
 const grid=page.frameLocator('iframe[title="wall_preview_inbox.wall_preview_gallery"]');await grid.locator('.card').first().waitFor();
 for(const label of ['CTA Clicks','Unique Clickers','Click → Open %','Avg Active Time','Median Active Time','Placement Rate','Preview → Cart %'])await page.locator('.sc-social-kpi').filter({hasText:label}).waitFor();
 console.log('Cold fixture startup to first gallery: '+(Date.now()-started)+'ms (includes browser startup)');
 await grid.getByRole('checkbox',{name:/Select Artwork 0 /}).check();await grid.getByRole('checkbox',{name:/Select Artwork 1 /}).check();assert.equal(await grid.locator('.selected').count(),2);await grid.getByRole('checkbox',{name:/Select Artwork 0 /}).uncheck();assert.equal(await grid.locator('.selected').count(),1);await grid.getByRole('button',{name:'Clear Selection'}).click();assert.equal(await grid.locator('.selected').count(),0);await grid.getByRole('checkbox',{name:'Select Visible',exact:true}).check();assert.equal(await grid.locator('.selected').count(),24);await grid.getByRole('button',{name:'Clear Selection'}).click();
 const sizes=[[320,568],[360,640],[375,667],[390,844],[430,932],[768,1024],[820,1180],[1024,1366],[1280,720],[1366,768],[1440,900],[1920,1080],[2560,1440],[844,390]];
 for(const [width,height] of sizes){await page.setViewportSize({width,height});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${width} page overflow`);assert.equal(await grid.locator('body').evaluate(b=>b.scrollWidth>innerWidth),false,`${width} grid overflow`);const columns=await grid.locator('.grid').evaluate(g=>getComputedStyle(g).gridTemplateColumns.split(' ').length);assert.ok(columns>=2,`${width} columns ${columns}`);console.log(`${width}x${height}: ${columns} columns, no overflow`)}
 await page.setViewportSize({width:1440,height:900});await grid.getByRole('button',{name:'View Artwork 0',exact:true}).click();
 const dialog=page.getByRole('dialog');await dialog.waitFor();await dialog.frameLocator('iframe').getByRole('button',{name:'Copy Image',exact:true}).waitFor();for(const [width,height] of sizes){await page.setViewportSize({width,height});await page.waitForTimeout(250);const box=await dialog.boundingBox();assert.ok(box.width<=width&&box.height<=height&&box.y+box.height<=height+1,`dialog exceeds ${width}x${height}`)}await page.setViewportSize({width:1440,height:900});const viewer=dialog.frameLocator('iframe');await viewer.getByRole('button',{name:'Copy Image',exact:true}).waitFor();
 await viewer.getByRole('button',{name:'Copy Image',exact:true}).click();await viewer.locator('#notice').filter({hasText:/copied|unavailable/}).waitFor();
 const downloaded=page.waitForEvent('download');await viewer.getByRole('button',{name:'Save Image'}).click();assert.ok((await downloaded).suggestedFilename().endsWith('.jpg'));
 await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});await grid.getByRole('button',{name:'View Artwork 0',exact:true}).click();await dialog.getByRole('button',{name:'Delete image',exact:true}).click();await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await dialog.waitFor({state:'hidden'});assert.equal(await grid.locator('.card').count(),24);
 await grid.getByRole('button',{name:'View Artwork 0',exact:true}).click();await dialog.getByRole('button',{name:'Delete image',exact:true}).click();await dialog.getByRole('button',{name:'Delete 1 Preview',exact:true}).click();await dialog.waitFor({state:'hidden'});await grid.getByRole('button',{name:'View Artwork 1',exact:true}).waitFor();assert.equal(await grid.getByRole('button',{name:'View Artwork 0',exact:true}).count(),0);
 for(let i=0;i<20;i++)await grid.locator('.select-card input').nth(i).check();await grid.getByRole('button',{name:'Delete Selected'}).click();await dialog.getByRole('button',{name:'Delete 20 Previews'}).waitFor();await page.setViewportSize({width:320,height:568});const confirmBox=await dialog.boundingBox();assert.ok(confirmBox.width<=320);await dialog.getByRole('button',{name:'Delete 20 Previews'}).click();await dialog.getByText('Another deletion is running. Please retry shortly.',{exact:true}).waitFor();assert.equal(await dialog.getByRole('button',{name:'Cancel',exact:true}).isEnabled(),true);await dialog.getByRole('button',{name:'Delete 20 Previews'}).click();await dialog.waitFor({state:'hidden'});await page.getByText('20 previews deleted or already removed.',{exact:true}).waitFor();await page.setViewportSize({width:1440,height:900});
 await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByText('Page 2 · 15 previews',{exact:true}).waitFor();await page.getByRole('button',{name:'Previous',exact:true}).click();await page.getByText('Page 1 · 24 previews',{exact:true}).waitFor();
 await page.getByRole('textbox',{name:'Search customer or product'}).fill('Artwork 59');await page.getByRole('textbox',{name:'Search customer or product'}).press('Enter');await grid.getByRole('button',{name:'View Artwork 59',exact:true}).waitFor();assert.equal(await grid.locator('.card').count(),1);
 await page.getByRole('button',{name:'Reset filters',exact:true}).click();await grid.locator('.card').nth(23).waitFor();await page.waitForFunction(()=>document.querySelector('input[aria-label="Search customer or product"]')?.value==='');assert.equal(errors.length,0,errors.join('\n'));await page.screenshot({path:require('node:path').join(require('node:os').tmpdir(),'sports-cave-social-inbox-fixture.png'),fullPage:true});
 console.log('PASS: 14 sizes; copy/fallback, download, cancel/delete, pagination, filter/reset; zero runtime errors');await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1});
