const assert=require('node:assert/strict');
const {SectionHistory,insertAt}=require('../components/crm_sections/history.js');
const h=new SectionHistory('A');h.record('B');h.record('B');
assert.equal(h.states.length,2);assert.equal(h.undo('B'),'A');assert.equal(h.redo(),'B');
assert.equal(h.undo('C'),'B');assert.equal(h.undo('B'),'A');h.record('D');assert.equal(h.redo(),'D');
const reloaded=new SectionHistory('D',JSON.parse(JSON.stringify(h)));assert.equal(reloaded.undo('D'),'A');
for(let i=0;i<100;i++)h.record(String(i));assert.equal(h.states.length,30);
for(let i=0;i<5;i++)h.record(String(i)+'x'.repeat(95000));assert.ok(h.states.length<=3);
assert.deepEqual(insertAt(['a','b','c'],'c','a',false),['c','a','b']);
assert.deepEqual(insertAt(['a','b','c'],'a','c',true),['b','c','a']);
assert.deepEqual(insertAt(['a','b','c'],'a','a',true),['a','b','c']);
console.log('10 bounded history, duplicate grouping, undo/redo, reload and insertion checks passed');
