// Loopback fixture only; Shopify, SQL and delivery are disposable/mocked.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const port=process.env.DISCOUNT_UI_PORT||8543,sqlPort=process.env.CRM_FIXTURE_SQL_PORT||8893;
const sql=async(sql,args=[])=>{const r=await fetch('http://127.0.0.1:'+sqlPort,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sql,args})});assert.ok(r.ok);return (await r.json()).rows;};
const wait=async(fn)=>{const end=Date.now()+20000;while(Date.now()<end){const value=await fn();if(value)return value;await new Promise(r=>setTimeout(r,100));}throw Error('State did not settle');};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext();await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
 const page=await context.newPage();page.setDefaultTimeout(20000);await page.setViewportSize({width:1440,height:950});
 page.on('pageerror',e=>console.error('BROWSER',e.message));
 await page.goto('http://127.0.0.1:'+port+'/?fixture_checkout=1&fixture_discount=1&fixture_steps=3&fixture_run=discountv2'+Date.now());
 await page.getByRole('button',{name:'Edit Email',exact:true}).nth(2).click();
 await page.getByRole('tab',{name:'Settings',exact:true}).click();
 assert.equal(await page.getByText('Apply Shopify discount automatically',{exact:true}).count(),0);
 assert.equal(await page.getByText('Recovery discount',{exact:true}).count(),0);
 await page.getByRole('tab',{name:'Editor',exact:true}).click();
 const frame=page.frameLocator('iframe[title="crm_section_ui.crm_middle_sections_v2"]');
 await frame.locator('#add summary').waitFor();
 const [flow]=await sql('SELECT id,config FROM crm_automations WHERE name=$1 ORDER BY updated_at DESC LIMIT 1',['Abandoned checkout · local fixture']);
 const config=async()=>(await sql('SELECT config FROM crm_automations WHERE id=$1',[flow.id]))[0].config;
 const open=async()=>{await frame.locator('#add summary').click();await frame.getByRole('button',{name:'Add Discount',exact:true}).click();};
 const start=Date.now();await open();await frame.getByRole('searchbox',{name:'Search Shopify discounts'}).waitFor();const openMs=Date.now()-start;
 const initial=Date.now();const pick=frame.getByRole('button',{name:'Select discount FIXTURE5',exact:true});await pick.waitFor();await wait(()=>pick.isEnabled());const initialMs=Date.now()-initial;
 assert.deepEqual(await config(),flow.config,'Opening and browsing must not write a draft');
 await page.screenshot({path:'.tmp_discount_picker.png',fullPage:true});
 const query=frame.getByRole('searchbox',{name:'Search Shopify discounts'});await query.fill('FIX');
 const began=Date.now();await frame.getByText('Loading Shopify discounts…',{exact:true}).waitFor();await wait(()=>pick.isEnabled());const searchMs=Date.now()-began;
 assert.ok(await query.evaluate(el=>el===document.activeElement),'Search completion retains input focus');
 assert.deepEqual(await config(),flow.config,'Searching must not write a draft');
 await frame.getByRole('button',{name:'Close discount selector'}).click();await frame.locator('#discount-picker').waitFor({state:'hidden'});
 await open();assert.equal(await query.inputValue(),'FIX');await wait(()=>pick.isEnabled());
 await pick.click();
 await frame.getByRole('textbox',{name:'Discount HTML',exact:true}).waitFor();
 const preview=page.frameLocator('.st-key-crm-composer-preview iframe[data-testid="stIFrame"]').getByText('AN EXCLUSIVE COLLECTOR OFFER',{exact:true});
 await preview.waitFor();
 let saved=await wait(async()=>{const c=await config();return c.draft.emails[2].document.recovery_discount?c:null;});
 assert.equal(saved.draft.emails[2].document.recovery_discount.code,'FIXTURE5');
 assert.deepEqual(saved.draft.emails.slice(0,2),flow.config.draft.emails.slice(0,2));
 assert.equal(saved.published_version,flow.config.published_version);
 const area=frame.getByRole('textbox',{name:'Discount HTML',exact:true});
 await area.fill((await area.inputValue()).replace('AN EXCLUSIVE COLLECTOR OFFER','YOUR COLLECTOR OFFER').replace('18px 22px','12px 16px').replace('{{discount_value}}',''));
 await wait(async()=>JSON.stringify(await config()).includes('YOUR COLLECTOR OFFER'));
 const visual=page.frameLocator('.st-key-crm-composer-preview iframe[data-testid="stIFrame"]');
 await visual.getByText('YOUR COLLECTOR OFFER',{exact:true}).waitFor();
 assert.equal(await visual.getByText('A$5 off',{exact:true}).count(),0);
 const codeOnly=await area.inputValue();
 await area.fill(codeOnly.replace('{{discount_code}}',''));
 await page.getByText(/Discount HTML needs attention: Keep/).waitFor();
 assert.equal(await page.locator('.st-key-crm-composer-preview iframe[data-testid="stIFrame"]').count(),0);
 assert.deepEqual((await config()).draft.emails[2].document.recovery_discount,saved.draft.emails[2].document.recovery_discount);
 await area.fill(codeOnly);await visual.getByText('YOUR COLLECTOR OFFER',{exact:true}).waitFor();
 const card=frame.locator('section.section').filter({has:frame.getByRole('button',{name:'Edit Discount',exact:true})});
 const handle=card.getByRole('button',{name:'Drag to reorder section; Alt + Up or Down'});
 await handle.press('Alt+ArrowUp');
 await wait(async()=>{const list=(await config()).draft.emails[2].document.middle_sections;return list.at(-1).type!=='discount';});
 assert.deepEqual((await config()).draft.emails[2].document.recovery_discount,saved.draft.emails[2].document.recovery_discount);
 await card.getByText('Hiding or deleting the last visible offer also removes its checkout discount from this draft.',{exact:true}).waitFor();
 await card.getByRole('button',{name:'Visible section — click to hide',exact:true}).click();
 await wait(async()=>!(await config()).draft.emails[2].document.recovery_discount);
 await card.getByRole('button',{name:'Hidden section — click to show',exact:true}).click();
 await wait(async()=>(await config()).draft.emails[2].document.recovery_discount);
 await page.screenshot({path:'.tmp_discount_desktop.png',fullPage:true});
 assert.equal(await page.getByTestId('stException').count(),0);
 await page.setViewportSize({width:390,height:950});await page.waitForTimeout(300);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
 await page.screenshot({path:'.tmp_discount_mobile.png',fullPage:true});
 await card.getByRole('button',{name:'Delete section',exact:true}).click();
 await card.getByRole('button',{name:'Confirm delete section',exact:true}).click();
 await wait(async()=>!(await config()).draft.emails[2].document.recovery_discount);
 assert.equal(await page.getByTestId('stException').count(),0);
 console.log(JSON.stringify({openMs,initialMs,searchMs,selection:true,editableHtml:true,move:true,hideRestore:true,remove:true,otherEmailsUnchanged:true,mobileOverflow:false}));
}catch(e){console.error(e);throw e;}finally{await browser.close();}})().catch(()=>process.exit(1));
