const assert=require('node:assert/strict'),fs=require('node:fs');
const {receivedBody}=require('../components/support_email/mail.js');
const rich=receivedBody({reader_document:'<html><body><b>Happy</b><img src="https://example.test/art.png"></body></html>'});
assert.ok(rich.includes('sandbox="allow-same-origin allow-popups allow-popups-to-escape-sandbox"'));
assert.ok(!rich.includes('allow-scripts'));assert.ok(!rich.includes('allow-forms'));
assert.ok(rich.includes('srcdoc="&lt;html&gt;'));assert.ok(rich.includes('referrerpolicy="no-referrer"'));
assert.equal(receivedBody({html:'<p>Plain fallback</p>'}),'<div class="message-body"><p>Plain fallback</p></div>');
const source=fs.readFileSync('components/support_email/mail.js','utf8');
assert.ok(source.includes("emit('load_visible_body',{message_key})"));
assert.ok(source.includes("emit('load_initial_mailbox')"));
assert.ok(source.includes("model.initial_load_pending?'Loading mailbox…'"));
assert.ok(source.includes('frame._emailObserver?.disconnect()'));
assert.ok(source.includes('new ResizeObserver(resize)'));
console.log('Received reader sandbox, escaping, fallback, deferred body and resize checks passed.');
