// Loopback fixture only, all Shopify and provider requests mocked.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const sql=async(sql,args=[])=>{const r=await fetch('http://127.0.0.1:8873',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sql,args})});assert.ok(r.ok);return (await r.json()).rows;};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext();await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
 const page=await context.newPage();page.setDefaultTimeout(20000);await page.setViewportSize({width:1440,height:950});
 await page.goto('http://127.0.0.1:8533/?fixture_checkout=1&fixture_discount=1&fixture_run=discount'+Date.now());
 await page.getByRole('button',{name:'Edit Email',exact:true}).first().click();
 await page.getByRole('tab',{name:'Settings',exact:true}).click();
 const [flow]=await sql('SELECT id,config FROM crm_automations WHERE name=$1 ORDER BY updated_at DESC LIMIT 1',['Abandoned checkout · local fixture']);
 const toggle=page.getByText('Apply Shopify discount automatically',{exact:true});await toggle.click();
 const open=page.getByRole('button',{name:'Select Shopify discount',exact:true});
 const start=Date.now();await open.click();await page.getByRole('textbox',{name:'Search code or name',exact:true}).waitFor();const openMs=Date.now()-start;
 assert.deepEqual((await sql('SELECT config FROM crm_automations WHERE id=$1',[flow.id]))[0].config,flow.config);
 await page.getByRole('textbox',{name:'Search code or name',exact:true}).fill('FIXTURE5');
 await page.getByRole('textbox',{name:'Search code or name',exact:true}).press('Tab');
 const began=Date.now();await page.getByRole('button',{name:'Search',exact:true}).click();
 await page.getByText('1 code loaded',{exact:true}).waitFor();
 const pick=page.getByRole('combobox',{name:'Shopify discount',exact:true});await pick.click();
 await page.getByRole('option',{name:/FIXTURE5/}).click();
 const searchMs=Date.now()-began;await page.getByRole('button',{name:'Use discount',exact:true}).click();
 await page.getByText('FIXTURE5 · A$5 off',{exact:true}).waitFor();
 await page.getByText('Discount: FIXTURE5 — A$5 off',{exact:false}).waitFor();
 const saved=(await sql('SELECT config FROM crm_automations WHERE id=$1',[flow.id]))[0].config;
 assert.equal(saved.draft.emails[0].document.recovery_discount.code,'FIXTURE5');assert.equal(saved.draft.emails[1].document.recovery_discount,undefined);
 assert.equal(await page.getByTestId('stException').count(),0);
 await page.getByRole('button',{name:'Clear discount',exact:true}).click();
 await page.waitForTimeout(500);assert.equal(await page.getByRole('button',{name:'Clear discount',exact:true}).count(),0);
 await page.setViewportSize({width:390,height:950});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
 console.log(JSON.stringify({openMs,searchMs,selection:true,clear:true,mobileOverflow:false}));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
