const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('components/sports_cave_top_bar/index.html','utf8');
const state={config:{revision:'user-a-v1',authToken:'token-a'},destroyed:false},requests=[];
const context={state,AbortController,parentWindow:{fetch:(url,options)=>new Promise(resolve=>requests.push({url,options,resolve}))}};
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('    const pendingReads ='),source.indexOf('    const topBarGreetingForDate ='))+'\nthis.read=requestJson;this.cancel=cancelPendingReads;',context);
const accept=(request,payload={ok:true})=>request.resolve({ok:true,json:async()=>payload});
(async()=>{
 const a=context.read('/status'),b=context.read('/status');assert.equal(a,b);assert.equal(requests.length,1);accept(requests[0]);await a;
 const c=context.read('/status');assert.equal(requests.length,2);accept(requests[1]);await c;
 const old=context.read('/status');state.config={revision:'user-b-v1',authToken:'token-b'};context.cancel();assert.equal(requests[2].options.signal.aborted,true);
 const fresh=context.read('/status');assert.equal(requests[3].options.headers.Authorization,'Bearer token-b');accept(requests[2]);await assert.rejects(old,{name:'AbortError'});accept(requests[3]);await fresh;
 const p=context.read('/save',{method:'POST',body:{a:1}}),q=context.read('/save',{method:'POST',body:{a:1}});assert.equal(requests.length,6);context.cancel();assert.equal(requests[4].options.signal,undefined);accept(requests[4]);accept(requests[5]);await Promise.all([p,q]);
 const unmounted=context.read('/status');state.destroyed=true;context.cancel();accept(requests[6]);await assert.rejects(unmounted,{name:'AbortError'});
 await assert.rejects(context.read('/status'),{name:'AbortError'});assert.equal(requests.length,7);
 const timers=[],timerContext={state:{destroyed:false},parentWindow:{setTimeout(fn){timers.push(fn);return timers.length;}}};
 vm.createContext(timerContext);vm.runInContext(source.slice(source.indexOf('    const timers = new Set();'),source.indexOf('    const state = {'))+'this.schedule=later;',timerContext);
 let calls=0;timerContext.schedule(()=>calls++,10);timerContext.state.destroyed=true;timers[0]();assert.equal(calls,0);
 assert.equal(timerContext.schedule(()=>calls++,10),null);assert.equal(timers.length,1);
 assert.ok(source.includes('cancelPendingReads();'));console.log('Shell GET deduplication, completion eviction, identity isolation, abort recovery, no mutation deduplication, and stale-response rejection passed.');
})().catch(e=>{console.error(e);process.exitCode=1});
