const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('components/sports_cave_top_bar/index.html','utf8');
let reads=0,writes=0,token='',observer;
const sidebar={getBoundingClientRect(){reads++;return {width:244}}};
const context={state:{destroyed:false},doc:{querySelector(){return sidebar},documentElement:{style:{getPropertyValue(){return token},setProperty(k,v){writes++;token=v}}}},parentWindow:{ResizeObserver:class {constructor(cb){this.cb=cb;observer=this}observe(){}disconnect(){this.disconnected=true}}}};
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('    let measuredSidebar ='),source.indexOf('    const handleViewportChange ='))+'this.measure=updateSidebarWidth;',context);
context.measure();context.measure();context.measure();
assert.equal(reads,1);assert.equal(writes,1);assert.equal(token,'244px');
observer.cb([{target:sidebar,borderBoxSize:[{inlineSize:244}]}]);
assert.equal(reads,1);assert.equal(writes,1);
observer.cb([{target:sidebar,borderBoxSize:[{inlineSize:238}]}]);
assert.equal(token,'238px');assert.equal(reads,1);assert.equal(writes,2);
context.state.destroyed=true;
observer.cb([{target:sidebar,borderBoxSize:[{inlineSize:260}]}]);
assert.equal(writes,2);
console.log('Observer-driven width: one initial layout read, stable reruns avoid reads/writes, resizing updates exact width, destroyed callbacks ignored.');
let presentationObserver,bindings=0;const timers=[],badges=[];
const cached={orders:{action_required_count:4,badge_label:'4'},email:{unread_count:125},wall:{wall_unread_count:99}};
const presentation={state:{destroyed:false},doc:{querySelector(){return sidebar}},parentWindow:{MutationObserver:class{constructor(cb){this.cb=cb;presentationObserver=this}observe(){}}},bindPersistentSidebarRoutes(){bindings++},readStatusCache(kind){return {payload:cached[kind]}},updateSidebarBadge(...args){badges.push(args)},later(fn){timers.push(fn);return timers.length}};
vm.createContext(presentation);
vm.runInContext(source.slice(source.indexOf('    let sidebarPresentationObserver ='),source.indexOf('    const reconcileAcceptedNavigation ='))+'this.watch=watchSidebarPresentation;',presentation);
presentation.watch();presentation.watch();
const changed=[{addedNodes:[{nodeType:1,matches(){return false},querySelector(){return {}}}],removedNodes:[]}];
presentationObserver.cb(changed);presentationObserver.cb(changed);
assert.equal(timers.length,1);timers.shift()();assert.equal(bindings,1);
assert.equal(badges.length,3);assert.equal(badges[1][1],125);
presentationObserver.cb([{addedNodes:[{nodeType:1,matches(){return false},querySelector(){return null}}],removedNodes:[]}]);
assert.equal(timers.length,0);
presentation.state.destroyed=true;presentationObserver.cb(changed);assert.equal(timers.length,0);
console.log('Fragment presentation: coalesced restore, cached badge counts, no badge observer loop, stale callbacks ignored.');
