const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto((process.env.FLOW_URL||'http://127.0.0.1:8893/')+'?fixture_checkout=1&fixture_wall_preview=1&fixture_run=wall'+Date.now());
 await page.getByRole('button',{name:'Edit Email',exact:true}).first().click();
 const subject=await page.getByRole('textbox',{name:'Subject',exact:true}).inputValue();
 await page.getByRole('tab',{name:'Templates',exact:true}).click();
 await page.locator('.st-key-library_builtin-wall-preview-section').getByRole('button',{name:'Use',exact:true}).click();
 await page.getByRole('tab',{name:'Editor',exact:true}).click();
 const editor=page.frameLocator('iframe[title="crm_section_ui.crm_middle_sections_v2"]');
 await editor.getByText('See It On Your Wall — Interactive Preview',{exact:true}).first().waitFor();
 const preview=page.frameLocator('.st-key-crm-composer-preview iframe');
 await preview.getByRole('heading',{name:'See It On Your Wall',exact:true}).waitFor();
 await preview.getByRole('link',{name:'SEE IT ON YOUR WALL',exact:true}).waitFor();
 const link=await preview.getByRole('link',{name:'SEE IT ON YOUR WALL',exact:true}).getAttribute('href');
 assert.equal(new URL(link).searchParams.get('variant'),'123');assert.equal(new URL(link).searchParams.get('sc_wall_preview'),'1');
 assert.ok(!link.includes('checkouts'));assert.ok(!link.includes('recover'));
 await preview.getByText(/complete your order/i).first().waitFor();
 await page.getByRole('button',{name:'Flow',exact:true}).click();
 await page.reload();await page.getByRole('button',{name:'Edit Email',exact:true}).first().click();
 assert.equal(await page.getByRole('textbox',{name:'Subject',exact:true}).inputValue(),subject);
 await page.getByRole('tab',{name:'Editor',exact:true}).click();
 await editor.getByText('See It On Your Wall — Interactive Preview',{exact:true}).first().waitFor();
 await preview.getByRole('heading',{name:'See It On Your Wall',exact:true}).waitFor();
 assert.equal(await page.getByTestId('stException').count(),0);assert.deepEqual(errors,[]);
 console.log('PASS Templates insertion, existing checkout preserved, preview variant link, draft persistence and reopening');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
