const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('components/sports_cave_top_bar/index.html','utf8');
let pending={route_key:'email',expected_epoch:4,navigation_id:7},cleared=0;
const root={dataset:{navigationEpoch:'4',acceptedNavigationId:'7',pendingRouteKey:'email'}};
const context={root,state:{config:{currentRouteKey:'email'}},doc:{body:{classList:{contains(){return !!root.dataset.pendingRouteKey}}}},readPendingNavigation:()=>pending,clearNavigationPending(){pending={};cleared++},mobileViewport:()=>false,closeMobileNavigation(){}};
vm.createContext(context);
const method=source.slice(source.indexOf('      completeNavigation({'),source.indexOf('      destroy({preserveDom'));
vm.runInContext('this.api={'+method+'};',context);
assert.equal(context.api.completeNavigation({routeKey:'email',epoch:3}),false);
assert.equal(context.api.completeNavigation({routeKey:'orders',epoch:4}),false);
assert.equal(cleared,0);
assert.equal(context.api.completeNavigation({routeKey:'email',epoch:4,status:'loading'}),true);
assert.equal(root.dataset.lastNavigationStatus,'loading');
context.api.completeNavigation({routeKey:'email',epoch:4,status:'ready'});
assert.equal(root.dataset.lastNavigationStatus,'ready');
context.api.completeNavigation({routeKey:'email',epoch:4,status:'loading'});
assert.equal(root.dataset.lastNavigationStatus,'ready');
root.dataset.navigationEpoch='5';context.state.config.currentRouteKey='orders';
assert.equal(context.api.completeNavigation({routeKey:'email',epoch:4}),false);
console.log('Readiness: essential loading can complete later, stale epochs/routes rejected, late shell cannot downgrade ready.');
