// Pure UI boundary helpers. End-to-end layout is checked with the local mock harness.
const assert=require('node:assert/strict');
const {esc,size,safeLink,locked,createViewCache,threadView}=require('../components/support_email/mail.js');
assert.equal(esc('<img src=x onerror="x">'), '&lt;img src=x onerror=&quot;x&quot;&gt;');
assert.equal(safeLink('javascript:alert(1)'), '');
assert.equal(safeLink('https://user:password@example.test'), '');
assert.equal(safeLink('https://example.test/path'), 'https://example.test/path');
assert.equal(size(1800000), '1.7 MB');
for (const status of ['accepted','unknown','in_progress']) assert.equal(locked({send_result:{status}}),true);
assert.ok(!locked({send_result:{status:'rejected'}}));
assert.equal(locked({send_result:{},draft_pending:true}),true);
const cache=createViewCache(2,100);
cache.put('a',{html:'first'});cache.put('b',{html:'second'});cache.get('a');cache.put('c',{html:'third'});
assert.equal(cache.get('b'),null);assert.equal(cache.get('a').html,'first');
cache.put('huge',{html:'x'.repeat(101)});assert.equal(cache.get('huge'),null);
assert.equal(cache.size,2);assert.ok(cache.bytes<=100);cache.clear();assert.equal(cache.size,0);
const messages=[{key:'older',folder:'INBOX',expanded:true},{key:'latest',folder:'INBOX',expanded:true},{key:'sent',folder:'Sent',expanded:false}];
const view=threadView(messages,'INBOX');
assert.equal(view.active_message,'latest');assert.deepEqual(view.messages.map(m=>m.expanded),[false,true,false]);
assert.equal(messages[0].expanded,true);assert.equal(threadView(messages,'Sent'),null);
console.log('Email component helper and bounded display-cache checks passed (20 assertions).');
