// Exercises the deployed theme. Only synthetic preview API writes are intercepted.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
const theme=process.env.SC_THEME_ID||'189335863603';
const sizes=[[320,568],[360,640],[375,667],[375,812],[390,844],[393,852],[412,915],[430,932],[568,320],[667,375],[844,390],[932,430],[768,1024],[820,1180],[1024,1366],[1280,720],[1366,768],[1440,900],[1920,1080],[2560,1440]];
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
try{
const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1',permissions:['camera'],acceptDownloads:true});let errors=[],captures=[];
page.on('pageerror',e=>errors.push(e.stack));
await page.route('**/api/wall-previews**',r=>{if(r.request().method()==='POST'&&!r.request().url().includes('/events'))captures.push(r.request().url());return r.fulfill({status:200,contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'*'},body:'{"ok":true,"archive_status":"queued","preview_id":"11111111-1111-4111-8111-111111111111"}'});});
await page.goto('https://www.sportscaveshop.com/products/legends-never-die-kobe-bryant-michael-jordan-wall-art'+(theme==='188890644787'?'':'?preview_theme_id='+theme),{waitUntil:'domcontentloaded'});
await page.waitForFunction(()=>window.Shopify?.theme?.id);assert.equal(String(await page.evaluate(()=>Shopify.theme.id)),theme);
await page.locator('[data-sc-wall-open]').waitFor();
console.log('Deployed assets',await page.locator('script[src*="sports-cave-wall-preview"],script[src*="sports-cave-image-protection"]').evaluateAll(es=>es.map(e=>e.src)));
// Shopify preview bar is DEV tooling, not storefront UI; hide via its own control where supplied.
const bar=page.frameLocator('#PBarNextFrame').getByRole('button',{name:/hide/i});try{await bar.first().waitFor({state:'visible',timeout:10000});await bar.first().click();}catch(e){}
const cookies=page.getByRole('button',{name:/reject all|decline/i});if(await cookies.count())await cookies.first().click();
for(const [width,height] of sizes){await page.setViewportSize({width,height});await page.locator('[data-sc-wall-open]').press('Enter');await page.waitForFunction(()=>document.querySelector('[data-sc-wall-camera-video]').readyState>=2);
const result=await page.evaluate(()=>['camera-capture','camera-library','camera-cancel'].map(s=>{let e=document.querySelector('[data-sc-wall-'+s+']'),r=e.getBoundingClientRect();return {s,x:r.x,y:r.y,w:r.width,h:r.height,visible:r.bottom<=innerHeight+1&&r.right<=innerWidth+1&&r.x>=0&&r.y>=0,hit:e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))};}));assert(result.every(r=>r.visible&&r.hit&&r.w>=44&&r.h>=44),JSON.stringify({width,height,result}));await page.locator('[data-sc-wall-camera-cancel]').click();await page.keyboard.press('Escape');await page.locator('[data-sc-wall-overlay]').waitFor({state:'hidden'});console.log('DEV camera PASS',width,height);}
await page.setViewportSize({width:390,height:844});await page.locator('[data-sc-wall-open]').press('Enter');await page.waitForFunction(()=>document.querySelector('[data-sc-wall-camera-video]').readyState>=2);await page.locator('[data-sc-wall-camera-capture]').click();await page.locator('[data-sc-wall-art]').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('video[data-sc-wall-camera-video]').srcObject===null);
await page.setViewportSize({width:568,height:320});await page.waitForTimeout(250);assert.equal(await page.locator('[data-sc-wall-rotate-guard]').count(),0);const controls=await page.locator('[data-sc-wall-sticky-secure],[data-sc-wall-size-grid],[data-sc-wall-save],[data-sc-wall-close]').evaluateAll(es=>es.map(e=>{let r=e.getBoundingClientRect();return {name:e.getAttribute('aria-label'),ok:r.x>=0&&r.y>=0&&r.bottom<=innerHeight+1&&r.right<=innerWidth+1};}));assert(controls.every(x=>x.ok),JSON.stringify(controls));console.log('PASS mobile landscape completed-preview controls');await page.setViewportSize({width:390,height:844});await page.waitForTimeout(250);
const art=await page.locator('[data-sc-wall-art]').boundingBox();await page.mouse.move(art.x+art.width/2,art.y+art.height/2);await page.mouse.down();await page.mouse.move(art.x+art.width/2+20,art.y+art.height/2+15,{steps:5});await page.mouse.up();await page.locator('[data-sc-wall-confirm]').click();await page.waitForFunction(()=>document.querySelector('[data-sc-wall-confirm-label]').textContent.includes('Your wall preview is ready'));
await page.locator('[data-sc-wall-save]').click();await page.locator('[data-sc-wall-download-email]').waitFor({state:'visible'});await page.locator('[data-sc-wall-download-name]').fill('Synthetic DEV Test');await page.locator('[data-sc-wall-download-email]').fill('preview-test@example.test');await page.locator('[data-sc-wall-download-consent]').uncheck();
const download=page.waitForEvent('download');await page.locator('[data-sc-wall-download-confirm]').click();await download;
await page.locator('[data-sc-wall-save]').click();const second=page.waitForEvent('download');await page.locator('[data-sc-wall-download-confirm]').click();await second;
await page.waitForTimeout(500);assert.equal(captures.length,3);assert.equal(new Set(captures.map(u=>new URL(u).searchParams.get('client_preview_id'))).size,3);
await page.screenshot({path:'output/deployed-wall-'+theme+'.png'});
console.log('PASS deployed shutter, drag, PLACE, two local Downloads, three distinct capture requests; storage writes intercepted');
console.log('Console errors',JSON.stringify(errors));fs.writeFileSync('output/deployed-wall-'+theme+'.json',JSON.stringify({theme,sizes,captures:captures.length,errors},null,2));
assert.equal(errors.filter(e=>!e.includes('boostymark-regionblock')).length,0,'new runtime errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
