const assert=require('node:assert/strict'),fs=require('fs'),crypto=require('crypto');
const {chromium}=require('playwright');const fixture=require('./wall_preview_completion_fixture.cjs');
const protection=process.env.SC_TEST_IMAGE_PROTECTION==='1';
const origin=protection?'https://www.sportscaveshop.com':'http://localhost:8999';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});let checks=0;
const assetsPage=await browser.newPage();
const assets=await assetsPage.evaluate(()=>{function png(w,h,color){let c=document.createElement('canvas');c.width=w;c.height=h;let x=c.getContext('2d');x.fillStyle=color;x.fillRect(0,0,w,h);return c.toDataURL().split(',')[1];}return {art:png(1000,1000,'navy'),room:png(1200,1600,'silver'),landscape:png(1600,1200,'silver')};});await assetsPage.close();
try{for(const [width,height,landscape] of [[320,568],[390,844],[412,915],[360,740],[844,390],[667,375],[768,1024],[1024,768],[1366,768],[1920,1080],[900,650],[390,844,true],[667,375,true],[768,1024,true],[1024,768,true],[1366,768,true]]){
const page=await browser.newPage({viewport:{width,height},acceptDownloads:true});let requests=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',async r=>{const u=r.request().url();if(protection && u.endsWith('/storefront-protection.js'))return r.fulfill({contentType:'application/javascript',body:fs.readFileSync('storefront-protection.js','utf8')});if(protection && u.endsWith('/api/storefront-protection/config'))return r.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:JSON.stringify({enabled:true})});if(u.includes('/api/wall-previews')){if(r.request().method()==='OPTIONS')return r.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'*'}});if(!u.includes('/events'))requests.push({url:new URL(u),bytes:r.request().postDataBuffer()});if(width===390&&requests.length===2&&!u.includes('/events'))await new Promise(resolve=>setTimeout(resolve,1500));return r.fulfill({status:width===412?503:200,contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:JSON.stringify({ok:true,archive_status:'queued',preview_id:'11111111-1111-4111-8111-111111111111'})});}if(u.endsWith('/art.png'))return r.fulfill({contentType:'image/png',body:Buffer.from(assets.art,'base64')});if(u===origin+'/products/test-art')return r.fulfill({contentType:'text/html',body:fixture()+(protection?'<script src="https://sports-cave-image-factory.onrender.com/storefront-protection.js" defer></script>':'')});return r.abort();});
await page.goto(origin+'/products/test-art');await page.locator('[data-sc-wall-open]').click();const originScroll=await page.evaluate(()=>window.scrollY);await page.locator('[data-sc-wall-upload-input]').setInputFiles({name:'room.png',mimeType:'image/png',buffer:Buffer.from(landscape?assets.landscape:assets.room,'base64')});await page.waitForTimeout(600);
const art=page.locator('[data-sc-wall-art]');await art.waitFor({state:'visible'});if(protection){await page.waitForFunction(()=>window.__scProtectionReady);assert.equal(await art.evaluate(e=>e.dispatchEvent(new Event('contextmenu',{bubbles:true,cancelable:true}))),false);}const box=await art.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+20,box.y+box.height/2+15,{steps:5});await page.mouse.up();await page.locator('[data-sc-wall-confirm]').click();
await page.waitForFunction(()=>document.querySelector('[data-sc-wall-confirm-label]').textContent==='✓ Your wall preview is ready');
await page.waitForTimeout(2100);assert.equal(await page.locator('[data-sc-wall-confirm-placement]').isVisible(),false);
const layout=await page.evaluate(()=>{const sels=['[data-sc-wall-sticky-secure]','[data-sc-wall-size-grid]','[data-sc-wall-save]','[data-sc-wall-close]'];return sels.map(s=>{let e=document.querySelector(s),r=e.getBoundingClientRect();return {s,x:r.x,y:r.y,w:r.width,h:r.height,visible:r.bottom<=innerHeight+1&&r.right<=innerWidth+1&&r.x>=-1&&r.y>=-1};});});
assert(layout.every(x=>x.visible),JSON.stringify({width,height,layout}));assert(layout[0].h>=40);assert.equal(errors.length,0,errors.join());assert(requests.length>=1,'Place saves');assert(requests[0].url.searchParams.get('client_preview_id').match(/^[0-9a-f-]{36}$/));assert.equal(requests[0].url.searchParams.has('image_reuse_allowed'),false);
if(width===390){await page.locator('[data-sc-wall-save]').click();await page.locator('[data-sc-wall-download-name]').fill('Test visitor');await page.locator('[data-sc-wall-download-email]').fill('test@example.test');await page.locator('[data-sc-wall-download-consent]').uncheck();const dl=page.waitForEvent('download');await page.locator('[data-sc-wall-download-confirm]').click();const downloaded=await dl;await page.waitForTimeout(300);assert.equal(hash(fs.readFileSync(await downloaded.path())),hash(requests[0].bytes));assert.equal(hash(requests[1].bytes),hash(requests[0].bytes));assert.notEqual(requests[1].url.searchParams.get('client_preview_id'),requests[0].url.searchParams.get('client_preview_id'));assert.equal(requests[1].url.searchParams.get('capture_mode'),'save_event');assert.equal(requests[1].url.searchParams.get('image_reuse_allowed'),'0');assert(!(await page.locator('[data-sc-wall-overlay]').innerText()).includes('Sports Cave copy saved.'));
// A second intentional Download must work while the prior archive is still pending.
await page.locator('[data-sc-wall-save]').click();assert.equal(await page.locator('[data-sc-wall-download-confirm]').isEnabled(),true);
const repeat=page.waitForEvent('download');await page.locator('[data-sc-wall-download-confirm]').click();await repeat;
await page.waitForTimeout(1800);assert.equal(requests.length,3);assert.equal(new Set(requests.map(r=>r.url.searchParams.get('client_preview_id'))).size,3);
assert.equal(hash(requests[2].bytes),hash(requests[1].bytes)); }
await page.screenshot({path:`output/completion-${width}x${height}${landscape?'-landscape-photo':''}.png`});
const keep=page.locator('[data-sc-wall-keep-browsing]');if(height<=600)assert.equal(await keep.isVisible(),false);else await keep.click();if(height<=600)await page.locator('[data-sc-wall-close]').first().click();assert.equal(await page.locator('[data-sc-wall-overlay]').isVisible(),false);assert(Math.abs(await page.evaluate(()=>scrollY)-originScroll)<2);assert.equal(page.url(),origin+'/products/test-art');
checks++;console.log(`PASS ${width}x${height}${landscape?' landscape photo':''}`);await page.close();}
}finally{await browser.close();}console.log(`${checks} viewport journeys passed`);})().catch(e=>{console.error(e);process.exitCode=1});
