# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9f3e6f021262ad99ece4c3ac987d1c4c"
name = "Sports Cave OS"
application_url = "https://sports-cave-image-factory.onrender.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_orders,read_products,write_products,read_files,write_files,read_images,write_images,read_inventory,read_locations,read_markets,read_metaobjects,read_metaobject_definitions,customer_read_customers,customer_read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
