CREATE TABLE IF NOT EXISTS os_protection_settings (
    singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
    policy jsonb NOT NULL DEFAULT '{}',
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS os_security_sessions (
    id text PRIMARY KEY CHECK (length(id)=64),
    user_id uuid NOT NULL,
    session_version integer NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    last_activity_at timestamptz NOT NULL DEFAULT now(),
    device text NOT NULL DEFAULT '',
    revoked_at timestamptz,
    locked_at timestamptz,
    reauthenticated_at timestamptz,
    failed_at timestamptz,
    cookie_grant_hash text UNIQUE,
    cookie_grant_expires_at timestamptz,
    cookie_claims jsonb,
    failed_attempts integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS os_security_sessions_user ON os_security_sessions (user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS os_security_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    user_id uuid,
    event text NOT NULL,
    resource text NOT NULL DEFAULT '',
    result text NOT NULL DEFAULT 'success',
    session_id text NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS os_security_audit_recent ON os_security_audit (occurred_at DESC);
CREATE INDEX IF NOT EXISTS os_security_audit_actor ON os_security_audit (user_id,occurred_at DESC);
CREATE TABLE IF NOT EXISTS os_security_login_limits (
    key text PRIMARY KEY,
    window_started_at timestamptz NOT NULL DEFAULT now(),
    attempts integer NOT NULL DEFAULT 1
);
ALTER TABLE os_security_login_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON os_security_login_limits FROM PUBLIC;
ALTER TABLE os_protection_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE os_security_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE os_security_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON os_protection_settings,os_security_sessions,os_security_audit FROM PUBLIC;
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN
        REVOKE ALL ON os_protection_settings,os_security_sessions,os_security_audit,os_security_login_limits FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN
        REVOKE ALL ON os_protection_settings,os_security_sessions,os_security_audit,os_security_login_limits FROM authenticated;
    END IF;
END $$;
