api_version = "2026-04"

[[extensions]]
name = "My Collection"
handle = "customer-certificate-vault"
uid = "ba32a77c-8dd1-4bae-dae7-fe481a4d4e7723e3ca05"
type = "ui_extension"

[[extensions.targeting]]
target = "customer-account.page.render"
module = "./src/MySportsCaveCollection.jsx"

[extensions.capabilities]
api_access = true
network_access = true

[extensions.settings]

[[extensions.settings.fields]]
key = "api_base_url"
type = "single_line_text_field"
name = "Collector Vault API URL"
description = "Sports Cave OS application URL used for authenticated Collector Vault requests."
